const KEY='kuku_preview_v4';
const INT=[600000,86400000,259200000,604800000,1209600000,2592000000,5184000000];
const ITEMS={food:{n:'ごはん',e:'🍙',xp:3,c:'food'},toy:{n:'おもちゃ',e:'🪀',xp:4,c:'play'},book:{n:'えほん',e:'📕',xp:5,c:'study'},gem:{n:'キラキラ',e:'💎',xp:8,c:null}};
const ST=[{m:0,n:'たまご'},{m:30,n:'あかちゃん'},{m:90,n:'こども'},{m:180,n:'せいちょう'},{m:320,n:'おとな'}];
const RO={study:{n:'チエポコ',c1:'#7eb5e3',c2:'#4f83b5',mark:'📘'},play:{n:'ハヤポコ',c1:'#ffc06c',c2:'#df7c2f',mark:'⚡'},food:{n:'モグポコ',c1:'#98cf88',c2:'#5f9c58',mark:'🌱'}};
let mem={};function get(k){try{return localStorage.getItem(k)}catch(e){return mem[k]||null}}function set(k,v){try{localStorage.setItem(k,v)}catch(e){mem[k]=v}}
function D(){let f={};for(let a=1;a<=9;a++)for(let b=1;b<=9;b++)f[`${a}x${b}`]={a,b,l:-1,d:0,at:0,ok:0,w:0,ms:0,ca:0,cok:0,cms:0};return{f,coins:0,streak:0,last:null,reward:null,settings:{challengeMin:3},pet:{xp:0,branch:null,care:{study:0,play:0,food:0},inv:{food:2,toy:1,book:1,gem:0},log:['ふしぎなたまごをもらった！']}}}
function load(){try{let base=D(),raw=JSON.parse(get(KEY)||'null')||{};let s={...base,...raw,settings:{...base.settings,...(raw.settings||{})},pet:{...base.pet,...(raw.pet||{}),care:{...base.pet.care,...(raw.pet?.care||{})},inv:{...base.pet.inv,...(raw.pet?.inv||{})}},f:{...base.f,...(raw.f||{})}};Object.values(s.f).forEach(f=>{if(f.ca==null)f.ca=0;if(f.cok==null)f.cok=0;if(f.cms==null)f.cms=0});return s}catch(e){return D()}}
let S=load(),ld=2,lb=1,ls=0,rq=[],ri=0,rs=0,ct=null,end=0,sc=0,co=0,cf=null,cs=0,challengeLocked=false;
const $=x=>document.getElementById(x);function save(){set(KEY,JSON.stringify(S))}function day(){let d=new Date;return d.toISOString().slice(0,10)}function stage(){let s=ST[0];for(let x of ST)if(S.pet.xp>=x.m)s=x;return s}function nextstage(){let s=stage(),i=ST.indexOf(s);return ST[Math.min(i+1,ST.length-1)]}
function branch(){if(S.pet.branch)return S.pet.branch;if(S.pet.xp<90)return null;let c=S.pet.care,k='study';if(c.play>c[k])k='play';if(c.food>c[k])k='food';S.pet.branch=k;S.pet.log.unshift(`${RO[k].n}ルートに進化！`);save();return k}
function fmt(t){if(!t)return'未学習';let d=t-Date.now();if(d<=0)return'復習できます';let m=Math.ceil(d/60000);if(m<60)return m+'分後';let h=Math.ceil(d/3600000);return h<24?h+'時間後':Math.ceil(d/86400000)+'日後'}
function lev(l){return['覚えたて','10分クリア','1日クリア','3日クリア','1週間クリア','2週間クリア','1か月クリア'][Math.max(0,l)]||'長期記憶'}
function diff(f){if(!f.at)return-1;let ac=f.ok/f.at,slow=Math.min(1,f.ms/7000),over=f.d<Date.now()?Math.min(1,(Date.now()-f.d)/(7*86400000)):0;return(1-ac)*.6+slow*.25+over*.15}
function duef(){return Object.values(S.f).filter(f=>f.l>=0&&f.d<=Date.now()).sort((a,b)=>diff(b)-diff(a))}
function rec(f,ok,ms,mode='study'){f.at++;f.ms=f.ms?Math.round(f.ms*.7+ms*.3):Math.round(ms);if(mode==='challenge'){f.ca++;if(ok)f.cok++;f.cms=f.cms?Math.round(f.cms*.7+ms*.3):Math.round(ms)}if(ok){f.ok++;f.l=f.l<0?0:Math.min(f.l+(ms<6000?1:0),INT.length-1);let iv=INT[Math.max(0,f.l)];if(ms<2500&&f.l>=2)iv*=1.2;if(ms>6000)iv*=.7;f.d=Date.now()+iv}else{f.w++;f.l=f.l<0?0:Math.max(0,f.l-2);f.d=Date.now()+300000}let t=day();if(S.last!==t){S.streak=S.last&&Math.round((new Date(t)-new Date(S.last))/86400000)===1?S.streak+1:1;S.last=t}save()}
function petSvg(){let s=stage(),b=branch(),cfg=b?RO[b]:{c1:'#e4b777',c2:'#b7793f',mark:''};if(s.n==='たまご')return`<svg class="pet-anim" viewBox="0 0 180 180"><defs><radialGradient id="egg" cx="35%" cy="25%"><stop offset="0" stop-color="#fffce9"/><stop offset=".6" stop-color="#f9dda0"/><stop offset="1" stop-color="#e8b85f"/></radialGradient><filter id="ds"><feDropShadow dx="0" dy="5" stdDeviation="4" flood-opacity=".22"/></filter></defs><g filter="url(#ds)"><ellipse cx="90" cy="99" rx="52" ry="67" fill="url(#egg)" stroke="#6a5133" stroke-width="6"/><ellipse class="shine" cx="69" cy="67" rx="13" ry="24" fill="#fff" opacity=".45"/><circle cx="69" cy="82" r="8" fill="#f3b45d"/><circle cx="111" cy="116" r="11" fill="#ef9b75"/><path d="M64 130 Q90 144 116 130" fill="none" stroke="#5c4630" stroke-width="5" stroke-linecap="round"/><path d="M53 44 Q90 18 127 44" fill="none" stroke="#fff8" stroke-width="4" stroke-linecap="round"/></g></svg>`;
let size=s.n==='あかちゃん'?1:s.n==='こども'?1.08:s.n==='せいちょう'?1.16:1.22;return`<svg class="pet-anim" viewBox="0 0 200 190"><defs><radialGradient id="body" cx="34%" cy="22%"><stop offset="0" stop-color="#fff" stop-opacity=".55"/><stop offset=".18" stop-color="${cfg.c1}"/><stop offset="1" stop-color="${cfg.c2}"/></radialGradient><radialGradient id="belly" cx="35%" cy="20%"><stop offset="0" stop-color="#fffdf6"/><stop offset="1" stop-color="#f3dfc0"/></radialGradient></defs><g transform="translate(100 98) scale(${size}) translate(-100 -98)"><path class="tail" d="M149 111 Q187 103 178 133 Q167 155 145 139" fill="${cfg.c2}" stroke="#584331" stroke-width="6" stroke-linecap="round"/><ellipse cx="100" cy="108" rx="57" ry="61" fill="url(#body)" stroke="#584331" stroke-width="6"/><circle class="earL" cx="58" cy="62" r="23" fill="${cfg.c1}" stroke="#584331" stroke-width="6"/><circle class="earR" cx="142" cy="62" r="23" fill="${cfg.c1}" stroke="#584331" stroke-width="6"/><ellipse cx="100" cy="125" rx="34" ry="30" fill="url(#belly)"/><ellipse class="shine" cx="75" cy="79" rx="18" ry="30" fill="#fff" opacity=".2"/><g class="eye"><ellipse cx="79" cy="99" rx="6" ry="8" fill="#2d2925"/></g><g class="eye"><ellipse cx="121" cy="99" rx="6" ry="8" fill="#2d2925"/></g><circle cx="100" cy="113" r="5" fill="#6a4738"/><path d="M87 124 Q100 135 113 124" fill="none" stroke="#4b3930" stroke-width="5" stroke-linecap="round"/><ellipse cx="63" cy="150" rx="22" ry="13" fill="${cfg.c2}" stroke="#584331" stroke-width="5"/><ellipse cx="137" cy="150" rx="22" ry="13" fill="${cfg.c2}" stroke="#584331" stroke-width="5"/><text x="100" y="48" text-anchor="middle" font-size="27">${cfg.mark}</text></g></svg>`}
function show(id){if(ct&&id!=='challenge'){clearInterval(ct);ct=null}document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.s===id));if(id==='home')home();if(id==='learn')learn();if(id==='petroom')petroom();if(id==='parent')parent()}
function home(){let du=duef(),nd=Object.values(S.f).filter(f=>f.l>=0&&f.d>Date.now()).sort((a,b)=>a.d-b.d)[0],st=stage(),ns=nextstage(),b=branch();$('due').textContent=du.length;$('nextdue').textContent=du.length?'今が復習タイミングです':nd?'次は '+fmt(nd.d):'まず1つの段を学習しよう';$('streak').textContent=S.streak;$('coins').textContent=S.coins;$('stage').textContent=st.n;$('petname').textContent=b?RO[b].n:'ポコ';$('petmsg').textContent=b?'育て方で進化したよ！':'どんな子に育つかな？';let from=st.m,to=ns===st?st.m+1:ns.m,p=ns===st?100:(S.pet.xp-from)/(to-from)*100;$('xpbar').style.width=Math.max(0,Math.min(100,p))+'%';$('xptext').textContent=ns===st?S.pet.xp+' XP':'次の成長まで '+Math.max(0,to-S.pet.xp)+' XP';$('petvis').innerHTML=petSvg();$('challengeHome').textContent=`⏱ ${S.settings.challengeMin}分チャレンジ`}
function learn(){$('dangrid').innerHTML='';for(let a=1;a<=9;a++){let b=document.createElement('button');b.textContent=a+'の段';b.onclick=()=>startLearn(a);$('dangrid').appendChild(b)}}
function startLearn(a){ld=a;lb=1;$('learnbox').style.display='block';nextLearn()}function nextLearn(){$('learnlabel').textContent=ld+'の段';$('learnq').textContent=ld+' × '+lb;$('learna').value='';$('learnfb').textContent='';ls=performance.now();setTimeout(()=>$('learna').focus(),80)}
function submitLearn(){if($('learna').value==='')return;let f=S.f[`${ld}x${lb}`],ans=ld*lb,ok=+$('learna').value===ans;rec(f,ok,performance.now()-ls,'learn');$('learnfb').className='feedback '+(ok?'ok':'ng');$('learnfb').textContent=ok?'正解！ 次は '+fmt(f.d):'答えは '+ans+'。5分後にもう一度';if(ok){S.coins++;S.pet.xp++;S.pet.care.study++;save()}setTimeout(()=>{lb++;if(lb>9){lb=1;modal('🎉',ld+'の段クリア！','復習は自動予約されました。');home()}else nextLearn()},500)}
function openReview(){rq=duef();ri=0;if(!rq.length){modal('✨','今は復習なし！','保護者→プレビュー確認用→「復習を期限に」でテストできます。');show('home');return}show('review');nextReview()}
function nextReview(){if(ri>=rq.length){finishReview();return}let f=rq[ri];$('reviewprog').textContent=`${ri+1}/${rq.length}`;$('reviewlevel').textContent=lev(f.l);$('reviewq').textContent=f.a+' × '+f.b;$('reviewa').value='';$('reviewfb').textContent='';$('reviewsched').textContent='';rs=performance.now();setTimeout(()=>$('reviewa').focus(),80)}
function submitReview(){if($('reviewa').value===''||ri>=rq.length)return;let f=rq[ri],ok=+$('reviewa').value===f.a*f.b;rec(f,ok,performance.now()-rs,'review');$('reviewfb').className='feedback '+(ok?'ok':'ng');$('reviewfb').textContent=ok?'正解！':'答えは '+f.a*f.b;$('reviewsched').textContent=ok?'次の復習：'+fmt(f.d):'5分後にもう一度';if(ok){S.coins+=2;S.pet.xp+=2;S.pet.care.study+=2;save()}setTimeout(()=>{ri++;nextReview()},500)}
function finishReview(){let text='今日の復習おつかれさま！';if(S.reward!==day()){let ks=['food','toy','book','gem'],k=ks[Math.floor(Math.random()*4)];S.pet.inv[k]=(S.pet.inv[k]||0)+1;S.reward=day();S.coins+=10;S.pet.xp+=8;S.pet.log.unshift('復習クリア！ '+ITEMS[k].n+'をGET');text=ITEMS[k].e+' '+ITEMS[k].n+' と10コインをGET！'}save();modal('🎁','復習クリア！',text);show('home')}
function randf(){let a=Object.values(S.f),w=[];for(let f of a){let n=1+(f.l<2?2:0)+(f.ca&&f.cok/f.ca<.75?3:0);for(let i=0;i<n;i++)w.push(f)}return w[Math.floor(Math.random()*w.length)]}
function startChallenge(){if(ct)clearInterval(ct);show('challenge');sc=co=0;challengeLocked=false;$('score').textContent=0;$('combo').textContent=0;$('challengeTitle').textContent=`${S.settings.challengeMin}分チャレンジ`;$('timer').textContent=`${S.settings.challengeMin}:00`;end=Date.now()+S.settings.challengeMin*60000;nextChallenge();ct=setInterval(()=>{let r=Math.max(0,end-Date.now()),s=Math.ceil(r/1000);$('timer').textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0');if(r<=0)finishChallenge()},250)}
function nextChallenge(){if(Date.now()>=end){finishChallenge();return}challengeLocked=false;cf=randf();$('challengeq').textContent=cf.a+' × '+cf.b;$('challengea').value='';$('challengefb').className='feedback';$('challengefb').innerHTML='';cs=performance.now();setTimeout(()=>$('challengea').focus(),50)}
function submitChallenge(){if(challengeLocked||$('challengea').value===''||!cf)return;challengeLocked=true;let ok=+$('challengea').value===cf.a*cf.b,ms=performance.now()-cs;rec(cf,ok,ms,'challenge');if(ok){sc++;co++;S.coins++;S.pet.xp++;S.pet.care.play++;$('challengefb').className='feedback ok';$('challengefb').textContent='○ 正解！'}else{co=0;$('challengefb').className='feedback ng';$('challengefb').innerHTML=`✕ ちがうよ<div class="wrong-answer">正解は ${cf.a*cf.b}</div>`}$('score').textContent=sc;$('combo').textContent=co;save();setTimeout(nextChallenge,ok?320:1050)}
function finishChallenge(){if(!ct)return;clearInterval(ct);ct=null;challengeLocked=true;let bonus=Math.max(3,Math.floor(sc/3));S.coins+=bonus;S.pet.xp+=Math.floor(sc/4);S.pet.care.play+=Math.floor(sc/5);save();modal('⏱',`${S.settings.challengeMin}分チャレンジ終了！`,sc+'問正解！ ボーナス '+bonus+'コイン');show('home')}
function petroom(){let st=stage(),ns=nextstage(),b=branch();$('petvis2').innerHTML=petSvg();$('petname2').textContent=b?RO[b].n:'ポコ';$('stage2').textContent=st.n;let from=st.m,to=ns===st?st.m+1:ns.m,p=ns===st?100:(S.pet.xp-from)/(to-from)*100;$('xpbar2').style.width=Math.max(0,Math.min(100,p))+'%';$('xptext2').textContent=ns===st?S.pet.xp+' XP':'次の成長まで '+Math.max(0,to-S.pet.xp)+' XP';let mx=Math.max(1,S.pet.care.study,S.pet.care.play,S.pet.care.food);for(let k of['study','play','food']){$(k+'bar').style.width=S.pet.care[k]/mx*100+'%';$(k+'v').textContent=S.pet.care[k]}$('inventory').innerHTML='';for(let [k,it] of Object.entries(ITEMS)){let n=S.pet.inv[k]||0,b=document.createElement('button');b.className='item';b.disabled=n<=0;b.innerHTML=`<div class="e">${it.e}</div><b>${it.n}</b><div class="tiny">×${n}</div>`;b.onclick=()=>useItem(k);$('inventory').appendChild(b)}$('log').innerHTML='';S.pet.log.slice(0,8).forEach(x=>{let r=document.createElement('div');r.className='row';r.textContent=x;$('log').appendChild(r)})}
function useItem(k){if(!S.pet.inv[k])return;let it=ITEMS[k],old=branch();S.pet.inv[k]--;S.pet.xp+=it.xp;if(it.c)S.pet.care[it.c]+=3;let nb=branch();S.pet.log.unshift(it.n+'を使った');save();petroom();home();document.querySelectorAll('.pet').forEach(x=>{x.classList.remove('pulse');void x.offsetWidth;x.classList.add('pulse')});if(!old&&nb)modal('✨','進化した！',RO[nb].n+'ルートになったよ！')}
function challengeRate(f){return f.ca?f.cok/f.ca:null}function ccls(f){if(!f.ca)return'none';let r=challengeRate(f);if(f.ca>=5&&r>=.9)return'master';if(r<.6)return'weak';if(r<.8)return'mid';return'good'}
function setChallengeMin(n){S.settings.challengeMin=n;save();document.querySelectorAll('[data-min]').forEach(b=>b.classList.toggle('active',+b.dataset.min===n));$('challengeSettingText').textContent=`現在：${n}分`;home()}
function parent(){let fs=Object.values(S.f),played=fs.filter(f=>f.ca),cat=played.reduce((s,f)=>s+f.ca,0),cok=played.reduce((s,f)=>s+f.cok,0);$('challengePlayed').textContent=played.length;$('challengeAccuracy').textContent=cat?Math.round(cok/cat*100)+'%':'—';$('challengeAttempts').textContent=cat;document.querySelectorAll('[data-min]').forEach(b=>b.classList.toggle('active',+b.dataset.min===S.settings.challengeMin));$('challengeSettingText').textContent=`現在：${S.settings.challengeMin}分`;let g=$('heat');g.innerHTML='<div></div>';for(let b=1;b<=9;b++){let h=document.createElement('div');h.className='hh';h.textContent=b;g.appendChild(h)}for(let a=1;a<=9;a++){let h=document.createElement('div');h.className='hh';h.textContent=a;g.appendChild(h);for(let b=1;b<=9;b++){let f=S.f[`${a}x${b}`],c=document.createElement('button');c.className='hc '+ccls(f);c.textContent=f.ca?Math.round(f.cok/f.ca*100)+'%':'—';c.onclick=()=>challengeDetail(f);g.appendChild(c)}}$('weaklist').innerHTML='';let w=played.slice().sort((a,b)=>(challengeRate(a)-challengeRate(b))||(b.ca-a.ca)).slice(0,6);if(!w.length)$('weaklist').innerHTML='<div class="row">まだチャレンジの記録がありません</div>';w.forEach(f=>{let r=document.createElement('div');r.className='row';r.innerHTML=`<b>${f.a}×${f.b}=${f.a*f.b}</b><span class="tiny">チャレンジ正答率 ${Math.round(f.cok/f.ca*100)}%（${f.cok}/${f.ca}）</span>`;$('weaklist').appendChild(r)})}
function challengeDetail(f){if(!f.ca){modal('📊',`${f.a} × ${f.b}`,'まだチャレンジでは出題されていません。');return}modal('📊',`${f.a} × ${f.b} = ${f.a*f.b}`,`チャレンジ正答率 ${Math.round(f.cok/f.ca*100)}%（${f.cok}/${f.ca}）／ 平均 ${(f.cms/1000).toFixed(1)}秒`)}
function demo(){S=D();let n=Date.now();for(let a=1;a<=9;a++)for(let b=1;b<=9;b++){let f=S.f[`${a}x${b}`];if((a+b)%3){f.at=8;f.ok=6;f.l=(a*b)%6;f.ms=2400+(a*b*211)%3000;f.d=n+(((a+b)%4)-2)*86400000;f.ca=3+((a*b)%8);let ratio=(a*b)%5===0?.45:(a+b)%4===0?.65:(a*b)%3===0?.82:.95;f.cok=Math.max(1,Math.round(f.ca*ratio));f.cms=1800+(a*b*173)%3600}}S.coins=74;S.streak=5;S.pet.xp=205;S.pet.care={study:24,play:10,food:15};S.pet.inv={food:4,toy:3,book:3,gem:1};S.pet.log.unshift('デモデータを読み込みました');save();home();modal('🧪','デモデータON','チャレンジ正答率マップ・進化・復習を確認できます。')}
function boost(){S.pet.xp+=80;branch();save();home();petroom();modal('✨','XP +80','育成画面で立体感と動きを確認してください。')}function makeDue(){Object.values(S.f).filter(f=>f.l>=0).forEach(f=>f.d=Date.now()-1000);save();home();modal('🧠','復習を期限にしました','ホームの「今日の復習」から確認できます。')}function resetAll(){S=D();save();location.reload()}
function modal(e,t,x){$('me').textContent=e;$('mt').textContent=t;$('mx').textContent=x;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show')}
for(let [id,fn] of[['learna',submitLearn],['reviewa',submitReview],['challengea',submitChallenge]])$(id).addEventListener('keydown',e=>{if(e.key==='Enter')fn()});home();learn();petroom();